# Generated by Django 3.2.4 on 2021-06-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userprofile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
