# Generated by Django 3.2.4 on 2021-06-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurb', '0003_blurbsfeed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlurbsFeed',
        ),
    ]
